// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeCommits(arg1:main.AnalyzePayload):Promise<main.AnalyzeResult>;

export function CancelAnalyze():Promise<void>;

export function CancelRefine():Promise<void>;

export function CheckConfig():Promise<boolean>;

export function GetConfig():Promise<main.Config>;

export function GetMeta():Promise<main.Meta>;

export function ListModels(arg1:main.AiConfig):Promise<main.ModelListResult>;

export function OpenConfigDir():Promise<void>;

export function PickDirectory():Promise<string>;

export function RefineReport(arg1:main.RefinePayload):Promise<main.AnalyzeResult>;

export function SaveConfig(arg1:main.Config):Promise<main.Config>;

export function SaveReport(arg1:string,arg2:string):Promise<main.SaveResult>;

export function ScanGit(arg1:main.ScanPayload):Promise<main.ScanResult>;

export function TestAI(arg1:main.AiConfig):Promise<main.TestResult>;
