// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeCommits(arg1) {
  return window['go']['main']['App']['AnalyzeCommits'](arg1);
}

export function CancelAnalyze() {
  return window['go']['main']['App']['CancelAnalyze']();
}

export function CancelRefine() {
  return window['go']['main']['App']['CancelRefine']();
}

export function CheckConfig() {
  return window['go']['main']['App']['CheckConfig']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMeta() {
  return window['go']['main']['App']['GetMeta']();
}

export function ListModels(arg1) {
  return window['go']['main']['App']['ListModels'](arg1);
}

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RefineReport(arg1) {
  return window['go']['main']['App']['RefineReport'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveReport(arg1, arg2) {
  return window['go']['main']['App']['SaveReport'](arg1, arg2);
}

export function ScanGit(arg1) {
  return window['go']['main']['App']['ScanGit'](arg1);
}

export function TestAI(arg1) {
  return window['go']['main']['App']['TestAI'](arg1);
}
